version: '3.8'
services:
  hapi-fhir:
    image: hapiproject/hapi:v6.2.0
    ports:
      - "8081:8080"
    container_name: hapi-fhir
    environment:
      - hapi.fhir.allow_external_references=true
      - hapi.fhir.allow_placeholder_references=true
      - hapi.fhir.reuse_cached_search_results_millis=0